#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use App\Command\RoutesCommand;

$config = Symfony\Component\Yaml\Yaml::parse(file_get_contents(__DIR__ . '/bootstrap/config.yml'));
$app = new Slim\App($config['settings']);

require __DIR__ . '/bootstrap/dependencies.php';

require __DIR__ . '/bootstrap/middleware.php';

require __DIR__ . '/bootstrap/controllers.php';

require __DIR__ . '/bootstrap/routes.php';

$application = new Application();

$application->add(new RoutesCommand($container['router']));

$application->run();
