#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use App\Command\RoutesCommand;
use App\Command\CreateUserCommand;
use App\Command\DatabaseCommand;

$config = Symfony\Component\Yaml\Yaml::parse(file_get_contents(__DIR__ . '/app/config.yml'))['config'];
$app = new Slim\App($config);

require __DIR__ . '/app/dependencies.php';

require __DIR__ . '/app/middleware.php';

require __DIR__ . '/app/controllers.php';

require __DIR__ . '/app/routes.php';

$application = new Application();

$application->add(new RoutesCommand($container));
$application->add(new CreateUserCommand($container));
$application->add(new DatabaseCommand());

$application->run();
